apiVersion: v1
kind: Service
metadata:
  name: addressbook
spec:
  type: NodePort
  selector:
    app: addressbook
  ports:
  - protocol: TCP
    port: 32760
    nodePort: 32760

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deployment
  labels:
    app: addressbook
spec:
  replicas: 6
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: ashish158/practice:tagVersion
        ports:
        - containerPort: 32760
